sudo: false
language: python
python:
- '3.5'
- '3.7'
os:
- 'linux'
env:
- TF="tensorflow"
- TF="tensorflow==1.14.0"
addons:
install: pip install $TF torch torchvision onnx
script:
- py.test -v
deploy:
  provider: pypi
  user: hakanardo
  password:
    secure: uE4YhjqfDHhAX75SLONa64CZBxuln8TJ/J7mvGdm7ZIU34Ct8su3NPOweoqQQDdoA4lSSK0wZpE9ND9167r9mZz7EkFt3/H1bPcoUC+t3+jEh52dEWG40xR517ViL8veokmrjDiLGCV2vfPor1/jBRMTvFO9xNRg1CoKMfU9AIhc/Vyc9oqLS0lT5cDRfgnh/ANLPzM89rZ8qsZflOaPObCzx+crtA2UI1hj9vCIwggSFD9VUMqW7+6o2jyptL92EQRjFY9y1LQnVuitE2plwfOpE9XN/fbhOOt1En6BD+Fw5d1jX1hnbqR5OXmB7GygWf2KIKxaOm35nICyfzXWhfh5wemSqhsFE5wo7dCIYlrcRtxd7A1JJlszdUNl+CYWPLd6S0PB7lA4ZbQ1MCF1ZE7Jco0idoCm8i6a9nXiYCYdzncto8HbxNqbt363QuJcLkqqNFTCN9B/TDOlSPrgCB4XWxS3iH6aDjSwDgdippUaDAaSP8k0La65XLex9EWwuk2PnXc5T+IFw6WD2VyXqfb0tRoGJeRhRmmfqIqPeRt8wuUy+MIMkfZ9yI3/vxeZMCtQ0jolGry4jgLBThf1ualoBanQE3PxAyMkjPLNXsr7XVO8FHXtNJvbgrXSk5rftmfomnFXhEGia48Ajt9KghiR70GXkLhQ3bCH2x5Fv9I=
  on:
    branch: stable
